/**
 * Reflow document repository — all SQL touching `reflow_documents` lives here
 * (ARCHITECTURE.md §3).
 *
 * Stores the whole generated reflow document for a book as one row, so entering
 * reflow mode is a single indexed read instead of re-extracting the PDF.
 *
 * `pageStarts` is deliberately NOT persisted: it is derived from the blocks by
 * `buildPageStarts`, and storing a derived index invites it drifting out of sync
 * with the blocks it describes. Rebuilding it on load is one linear pass.
 */
import {
  buildPageStarts,
  REFLOW_FORMAT_VERSION,
  type ReflowDocument,
  type TextBlock,
} from '@/core/entities/reflowDocument';
import { DomainError } from '@/core/errors';
import type { DatabaseConnection } from '@/data/db/connection';

/** What the caller supplies; the rest is derived or defaulted. */
export interface NewReflowDocument {
  bookId: string;
  sourceFingerprint: string;
  pageCount: number;
  blocks: TextBlock[];
}

/** Row shape as stored. */
interface ReflowDocumentRow {
  book_id: string;
  format_version: number;
  source_fingerprint: string;
  page_count: number;
  block_count: number;
  blocks: string;
  generated_at: number;
}

export interface ReflowDocumentRepository {
  /**
   * Loads a book's document, or null when none is stored.
   *
   * Returns whatever is stored regardless of version; validity is the caller's
   * decision (see `isReflowDocumentUsable`) so a stale document can be reported
   * distinctly from a missing one.
   */
  findByBook(bookId: string): Promise<ReflowDocument | null>;
  /**
   * Loads a document only if it is usable for this fingerprint and the current
   * format version. One indexed query, no JSON parsing on a miss.
   */
  findUsable(bookId: string, sourceFingerprint: string): Promise<ReflowDocument | null>;
  /** Inserts or replaces a book's document. */
  save(input: NewReflowDocument, now?: Date): Promise<ReflowDocument>;
  /** Deletes a book's document. Returns true when a row was removed. */
  deleteForBook(bookId: string): Promise<boolean>;
  /** Deletes every document generated by an older format version. */
  deleteStaleVersions(currentVersion?: number): Promise<number>;
}

const COLUMNS =
  'book_id, format_version, source_fingerprint, page_count, block_count, blocks, generated_at';

/**
 * Rehydrates a row.
 *
 * A corrupt `blocks` payload is reported as a miss rather than thrown: the caller
 * regenerates, which is strictly better than an unreadable book. Anything else
 * (schema drift, wrong types) is a genuine bug and surfaces as a DomainError.
 */
function toReflowDocument(row: ReflowDocumentRow): ReflowDocument | null {
  let blocks: TextBlock[];
  try {
    const parsed: unknown = JSON.parse(row.blocks);
    if (!Array.isArray(parsed)) return null;
    blocks = parsed as TextBlock[];
  } catch {
    return null;
  }

  return {
    bookId: row.book_id,
    formatVersion: row.format_version,
    sourceFingerprint: row.source_fingerprint,
    pageCount: row.page_count,
    blocks,
    pageStarts: buildPageStarts(blocks, row.page_count),
    generatedAt: new Date(row.generated_at),
  };
}

export function createReflowDocumentRepository(
  db: DatabaseConnection,
): ReflowDocumentRepository {
  async function findByBook(bookId: string): Promise<ReflowDocument | null> {
    const row = await db.getFirstAsync<ReflowDocumentRow>(
      `SELECT ${COLUMNS} FROM reflow_documents WHERE book_id = ?`,
      [bookId],
    );
    return row ? toReflowDocument(row) : null;
  }

  return {
    findByBook,

    async findUsable(bookId, sourceFingerprint) {
      const row = await db.getFirstAsync<ReflowDocumentRow>(
        `SELECT ${COLUMNS} FROM reflow_documents
         WHERE book_id = ? AND format_version = ? AND source_fingerprint = ?`,
        [bookId, REFLOW_FORMAT_VERSION, sourceFingerprint],
      );
      return row ? toReflowDocument(row) : null;
    },

    async save(input, now = new Date()) {
      if (!Number.isInteger(input.pageCount) || input.pageCount < 0) {
        throw new DomainError(
          'unknown',
          `pageCount must be a non-negative integer, received ${input.pageCount}`,
        );
      }

      const serialized = JSON.stringify(input.blocks);

      try {
        await db.runAsync(
          `INSERT INTO reflow_documents (${COLUMNS})
           VALUES (?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(book_id) DO UPDATE SET
             format_version = excluded.format_version,
             source_fingerprint = excluded.source_fingerprint,
             page_count = excluded.page_count,
             block_count = excluded.block_count,
             blocks = excluded.blocks,
             generated_at = excluded.generated_at`,
          [
            input.bookId,
            REFLOW_FORMAT_VERSION,
            input.sourceFingerprint,
            input.pageCount,
            input.blocks.length,
            serialized,
            now.getTime(),
          ],
        );
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        if (/FOREIGN KEY/i.test(message)) {
          throw new DomainError('book_not_found', `No book with id ${input.bookId}`, error);
        }
        throw error;
      }

      const saved = await findByBook(input.bookId);
      if (!saved) {
        throw new DomainError(
          'unknown',
          `Reflow document for book ${input.bookId} vanished immediately after save`,
        );
      }
      return saved;
    },

    async deleteForBook(bookId) {
      const result = await db.runAsync('DELETE FROM reflow_documents WHERE book_id = ?', [bookId]);
      return result.changes > 0;
    },

    async deleteStaleVersions(currentVersion = REFLOW_FORMAT_VERSION) {
      const result = await db.runAsync('DELETE FROM reflow_documents WHERE format_version != ?', [
        currentVersion,
      ]);
      return result.changes;
    },
  };
}
